[package]
name = "npw-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
npw-core = { path = "../npw-core" }
serde.workspace = true
