[package]
name = "npw-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fs2.workspace = true
thiserror.workspace = true
